name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "todo"]
assignees:
  - mascheiber
  - Chris-Bee
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: checkboxes
    id: issue-check
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: "\"default dockerimage\" or \"Ubuntu 20.04\""
    validations:
      required: true

  - type: input
    id: hardware
    attributes:
      label: Hardware
      description: Which hardware are you using?
      placeholder: "\"RPi4\" or \"Desktop PC\""
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Flight Stack Version
      description: Which version of the flight stack are you using?
      placeholder: 1.0.0
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the bug behavior.
      placeholder: |
        1. Hardware switched on...
        2. Flight Stack started with...
        3. Execute mission...
        4. See error...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.

        Tip: This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: |
        Do you have any additional context about the issue you are seeing (links, references)?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
