name: Feature Request
description: Suggest a new feature for this project
title: "[Feature]: "
labels: ["feature", "request", "todo"]
assignees:
  - mascheiber
  - Chris-Bee
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: Summarize the problem this feature should solve precisely.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Desired Solution/Behavior
      description: Describe clear and concise what you would like to happen.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: |
        Do you have any additional context about the issue you are seeing (links, references)? Please also provide alternative solutions, if you think of any.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
